### ISSUE TITLE
AttributeError: '_Collection' object has no attribute 'find_cards'

### ISSUE THREAD

**Issue by RadekZareba** [brownbat/autoEaseFactor#12] opened 2020-09-12 13:56 UTC
Windows 10
Anki version 2.1.22

I can see this after adjust ease factors to performance.

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-12 14:22:25

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Radoslaw Zareba\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 299, in <lambda>
    did=deck_id: adjust_ease_factors(did))
  File "C:\Users\Radoslaw Zareba\AppData\Roaming\Anki2\addons21\1672712021\autoEaseFactor.py", line 225, in adjust_ease_factors
    card_ids = mw.col.find_cards(f'deck:"{deck_name}"')
AttributeError: '_Collection' object has no attribute 'find_cards'

**Comment by brownbat** [comment] 2020-09-12 14:56
Closing as this is a duplicate of #11 --- latest version should fix for 2.1.26+, but no longer includes the option for 2.1.22 unfortunately. 2.1.22 had a different architecture for finding cards and will take a bit more development...

**Closed as completed** 2020-09-12 14:57 UTC
